// Code generated by CoroutineEventCodeGen.py

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace miniRAID
{
    public class SequentialAny<T> where T : Delegate
    {
        private List<T> listeners = new();

        public bool Invoke(params object[] vs)
        {
            foreach (var e in listeners.ToList())
            {
                var result = (bool)(e.DynamicInvoke(vs));
                if (result)
                {
                    return true;
                }
            }

            return false;
        }

        public bool InvokeWhenNot(bool initialValue, params object[] vs)
        {
            return initialValue || Invoke(vs);
        }
        
        public static SequentialAny<T> operator +(SequentialAny<T> evt, T listener)
        {
            if(evt == null) { evt = new(); }

            if(!evt.listeners.Contains(listener))
            {
                evt.listeners.Add(listener);
            }

            return evt;
        }

        public static SequentialAny<T> operator -(SequentialAny<T> evt, T listener)
        {
            if(evt == null) { return null; }

            if (evt.listeners.Contains(listener))
            {
                evt.listeners.Remove(listener);
            }

            return evt;
        }
    }
    
    public class CoroutineEvent<T0>
    {
        HashSet<Func<T0, IEnumerator>> listeners = new();

        public IEnumerator Invoke(params object[] vs)
        {
            foreach (var e in listeners.ToList())
            {
                yield return new JumpIn((IEnumerator)e.DynamicInvoke(vs));
            }
            yield break;
        }

        static Func<T0, IEnumerator> Wrapper(Action<T0> infunc)
        {
            IEnumerator foo(T0 a) // TArgs
            {
                infunc.Invoke(a); // TParams
                yield break;
            }

            return foo;
        }

        public static CoroutineEvent<T0> operator +(CoroutineEvent<T0> evt, Func<T0, IEnumerator> listener)
        {
            if(evt == null) { evt = new(); }

            if(!evt.listeners.Contains(listener))
            {
                evt.listeners.Add(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0> operator +(CoroutineEvent<T0> evt, Action<T0> listener)
        {
            return evt + Wrapper(listener);
        }

        public static CoroutineEvent<T0> operator -(CoroutineEvent<T0> evt, Func<T0, IEnumerator> listener)
        {
            if(evt == null) { return null; }

            if (evt.listeners.Contains(listener))
            {
                evt.listeners.Remove(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0> operator -(CoroutineEvent<T0> evt, Action<T0> listener)
        {
            return evt - Wrapper(listener);
        }
    }

    public class CoroutineEvent<T0, T1>
    {
        HashSet<Func<T0, T1, IEnumerator>> listeners = new();

        public IEnumerator Invoke(params object[] vs)
        {
            foreach (var e in listeners.ToList())
            {
                yield return new JumpIn((IEnumerator)e.DynamicInvoke(vs));
            }
            yield break;
        }

        static Func<T0, T1, IEnumerator> Wrapper(Action<T0, T1> infunc)
        {
            IEnumerator foo(T0 a, T1 b) // TArgs
            {
                infunc.Invoke(a, b); // TParams
                yield break;
            }

            return foo;
        }

        public static CoroutineEvent<T0, T1> operator +(CoroutineEvent<T0, T1> evt, Func<T0, T1, IEnumerator> listener)
        {
            if(evt == null) { evt = new(); }

            if(!evt.listeners.Contains(listener))
            {
                evt.listeners.Add(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1> operator +(CoroutineEvent<T0, T1> evt, Action<T0, T1> listener)
        {
            return evt + Wrapper(listener);
        }

        public static CoroutineEvent<T0, T1> operator -(CoroutineEvent<T0, T1> evt, Func<T0, T1, IEnumerator> listener)
        {
            if(evt == null) { return null; }

            if (evt.listeners.Contains(listener))
            {
                evt.listeners.Remove(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1> operator -(CoroutineEvent<T0, T1> evt, Action<T0, T1> listener)
        {
            return evt - Wrapper(listener);
        }
    }

    public class CoroutineEvent<T0, T1, T2>
    {
        HashSet<Func<T0, T1, T2, IEnumerator>> listeners = new();

        public IEnumerator Invoke(params object[] vs)
        {
            foreach (var e in listeners.ToList())
            {
                yield return new JumpIn((IEnumerator)e.DynamicInvoke(vs));
            }
            yield break;
        }

        static Func<T0, T1, T2, IEnumerator> Wrapper(Action<T0, T1, T2> infunc)
        {
            IEnumerator foo(T0 a, T1 b, T2 c) // TArgs
            {
                infunc.Invoke(a, b, c); // TParams
                yield break;
            }

            return foo;
        }

        public static CoroutineEvent<T0, T1, T2> operator +(CoroutineEvent<T0, T1, T2> evt, Func<T0, T1, T2, IEnumerator> listener)
        {
            if(evt == null) { evt = new(); }

            if(!evt.listeners.Contains(listener))
            {
                evt.listeners.Add(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2> operator +(CoroutineEvent<T0, T1, T2> evt, Action<T0, T1, T2> listener)
        {
            return evt + Wrapper(listener);
        }

        public static CoroutineEvent<T0, T1, T2> operator -(CoroutineEvent<T0, T1, T2> evt, Func<T0, T1, T2, IEnumerator> listener)
        {
            if(evt == null) { return null; }

            if (!evt.listeners.Contains(listener))
            {
                evt.listeners.Remove(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2> operator -(CoroutineEvent<T0, T1, T2> evt, Action<T0, T1, T2> listener)
        {
            return evt - Wrapper(listener);
        }
    }

    public class CoroutineEvent<T0, T1, T2, T3>
    {
        HashSet<Func<T0, T1, T2, T3, IEnumerator>> listeners = new();

        public IEnumerator Invoke(params object[] vs)
        {
            foreach (var e in listeners.ToList())
            {
                yield return new JumpIn((IEnumerator)e.DynamicInvoke(vs));
            }
            yield break;
        }

        static Func<T0, T1, T2, T3, IEnumerator> Wrapper(Action<T0, T1, T2, T3> infunc)
        {
            IEnumerator foo(T0 a, T1 b, T2 c, T3 d) // TArgs
            {
                infunc.Invoke(a, b, c, d); // TParams
                yield break;
            }

            return foo;
        }

        public static CoroutineEvent<T0, T1, T2, T3> operator +(CoroutineEvent<T0, T1, T2, T3> evt, Func<T0, T1, T2, T3, IEnumerator> listener)
        {
            if(evt == null) { evt = new(); }

            if(!evt.listeners.Contains(listener))
            {
                evt.listeners.Add(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2, T3> operator +(CoroutineEvent<T0, T1, T2, T3> evt, Action<T0, T1, T2, T3> listener)
        {
            return evt + Wrapper(listener);
        }

        public static CoroutineEvent<T0, T1, T2, T3> operator -(CoroutineEvent<T0, T1, T2, T3> evt, Func<T0, T1, T2, T3, IEnumerator> listener)
        {
            if(evt == null) { return null; }

            if (!evt.listeners.Contains(listener))
            {
                evt.listeners.Remove(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2, T3> operator -(CoroutineEvent<T0, T1, T2, T3> evt, Action<T0, T1, T2, T3> listener)
        {
            return evt - Wrapper(listener);
        }
    }

    public class CoroutineEvent<T0, T1, T2, T3, T4>
    {
        HashSet<Func<T0, T1, T2, T3, T4, IEnumerator>> listeners = new();

        public IEnumerator Invoke(params object[] vs)
        {
            foreach (var e in listeners.ToList())
            {
                yield return new JumpIn((IEnumerator)e.DynamicInvoke(vs));
            }
            yield break;
        }

        static Func<T0, T1, T2, T3, T4, IEnumerator> Wrapper(Action<T0, T1, T2, T3, T4> infunc)
        {
            IEnumerator foo(T0 a, T1 b, T2 c, T3 d, T4 e) // TArgs
            {
                infunc.Invoke(a, b, c, d, e); // TParams
                yield break;
            }

            return foo;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4> operator +(CoroutineEvent<T0, T1, T2, T3, T4> evt, Func<T0, T1, T2, T3, T4, IEnumerator> listener)
        {
            if(evt == null) { evt = new(); }

            if(!evt.listeners.Contains(listener))
            {
                evt.listeners.Add(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4> operator +(CoroutineEvent<T0, T1, T2, T3, T4> evt, Action<T0, T1, T2, T3, T4> listener)
        {
            return evt + Wrapper(listener);
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4> operator -(CoroutineEvent<T0, T1, T2, T3, T4> evt, Func<T0, T1, T2, T3, T4, IEnumerator> listener)
        {
            if(evt == null) { return null; }

            if (!evt.listeners.Contains(listener))
            {
                evt.listeners.Remove(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4> operator -(CoroutineEvent<T0, T1, T2, T3, T4> evt, Action<T0, T1, T2, T3, T4> listener)
        {
            return evt - Wrapper(listener);
        }
    }

    public class CoroutineEvent<T0, T1, T2, T3, T4, T5>
    {
        HashSet<Func<T0, T1, T2, T3, T4, T5, IEnumerator>> listeners = new();

        public IEnumerator Invoke(params object[] vs)
        {
            foreach (var e in listeners.ToList())
            {
                yield return new JumpIn((IEnumerator)e.DynamicInvoke(vs));
            }
            yield break;
        }

        static Func<T0, T1, T2, T3, T4, T5, IEnumerator> Wrapper(Action<T0, T1, T2, T3, T4, T5> infunc)
        {
            IEnumerator foo(T0 a, T1 b, T2 c, T3 d, T4 e, T5 f) // TArgs
            {
                infunc.Invoke(a, b, c, d, e, f); // TParams
                yield break;
            }

            return foo;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5> operator +(CoroutineEvent<T0, T1, T2, T3, T4, T5> evt, Func<T0, T1, T2, T3, T4, T5, IEnumerator> listener)
        {
            if(evt == null) { evt = new(); }

            if(!evt.listeners.Contains(listener))
            {
                evt.listeners.Add(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5> operator +(CoroutineEvent<T0, T1, T2, T3, T4, T5> evt, Action<T0, T1, T2, T3, T4, T5> listener)
        {
            return evt + Wrapper(listener);
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5> operator -(CoroutineEvent<T0, T1, T2, T3, T4, T5> evt, Func<T0, T1, T2, T3, T4, T5, IEnumerator> listener)
        {
            if(evt == null) { return null; }

            if (!evt.listeners.Contains(listener))
            {
                evt.listeners.Remove(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5> operator -(CoroutineEvent<T0, T1, T2, T3, T4, T5> evt, Action<T0, T1, T2, T3, T4, T5> listener)
        {
            return evt - Wrapper(listener);
        }
    }

    public class CoroutineEvent<T0, T1, T2, T3, T4, T5, T6>
    {
        HashSet<Func<T0, T1, T2, T3, T4, T5, T6, IEnumerator>> listeners = new();

        public IEnumerator Invoke(params object[] vs)
        {
            foreach (var e in listeners.ToList())
            {
                yield return new JumpIn((IEnumerator)e.DynamicInvoke(vs));
            }
            yield break;
        }

        static Func<T0, T1, T2, T3, T4, T5, T6, IEnumerator> Wrapper(Action<T0, T1, T2, T3, T4, T5, T6> infunc)
        {
            IEnumerator foo(T0 a, T1 b, T2 c, T3 d, T4 e, T5 f, T6 g) // TArgs
            {
                infunc.Invoke(a, b, c, d, e, f, g); // TParams
                yield break;
            }

            return foo;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5, T6> operator +(CoroutineEvent<T0, T1, T2, T3, T4, T5, T6> evt, Func<T0, T1, T2, T3, T4, T5, T6, IEnumerator> listener)
        {
            if(evt == null) { evt = new(); }

            if(!evt.listeners.Contains(listener))
            {
                evt.listeners.Add(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5, T6> operator +(CoroutineEvent<T0, T1, T2, T3, T4, T5, T6> evt, Action<T0, T1, T2, T3, T4, T5, T6> listener)
        {
            return evt + Wrapper(listener);
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5, T6> operator -(CoroutineEvent<T0, T1, T2, T3, T4, T5, T6> evt, Func<T0, T1, T2, T3, T4, T5, T6, IEnumerator> listener)
        {
            if(evt == null) { return null; }

            if (!evt.listeners.Contains(listener))
            {
                evt.listeners.Remove(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5, T6> operator -(CoroutineEvent<T0, T1, T2, T3, T4, T5, T6> evt, Action<T0, T1, T2, T3, T4, T5, T6> listener)
        {
            return evt - Wrapper(listener);
        }
    }

    public class CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7>
    {
        HashSet<Func<T0, T1, T2, T3, T4, T5, T6, T7, IEnumerator>> listeners = new();

        public IEnumerator Invoke(params object[] vs)
        {
            foreach (var e in listeners.ToList())
            {
                yield return new JumpIn((IEnumerator)e.DynamicInvoke(vs));
            }
            yield break;
        }

        static Func<T0, T1, T2, T3, T4, T5, T6, T7, IEnumerator> Wrapper(Action<T0, T1, T2, T3, T4, T5, T6, T7> infunc)
        {
            IEnumerator foo(T0 a, T1 b, T2 c, T3 d, T4 e, T5 f, T6 g, T7 h) // TArgs
            {
                infunc.Invoke(a, b, c, d, e, f, g, h); // TParams
                yield break;
            }

            return foo;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7> operator +(CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7> evt, Func<T0, T1, T2, T3, T4, T5, T6, T7, IEnumerator> listener)
        {
            if(evt == null) { evt = new(); }

            if(!evt.listeners.Contains(listener))
            {
                evt.listeners.Add(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7> operator +(CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7> evt, Action<T0, T1, T2, T3, T4, T5, T6, T7> listener)
        {
            return evt + Wrapper(listener);
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7> operator -(CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7> evt, Func<T0, T1, T2, T3, T4, T5, T6, T7, IEnumerator> listener)
        {
            if(evt == null) { return null; }

            if (!evt.listeners.Contains(listener))
            {
                evt.listeners.Remove(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7> operator -(CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7> evt, Action<T0, T1, T2, T3, T4, T5, T6, T7> listener)
        {
            return evt - Wrapper(listener);
        }
    }

    public class CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7, T8>
    {
        HashSet<Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, IEnumerator>> listeners = new();

        public IEnumerator Invoke(params object[] vs)
        {
            foreach (var e in listeners.ToList())
            {
                yield return new JumpIn((IEnumerator)e.DynamicInvoke(vs));
            }
            yield break;
        }

        static Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, IEnumerator> Wrapper(Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> infunc)
        {
            IEnumerator foo(T0 a, T1 b, T2 c, T3 d, T4 e, T5 f, T6 g, T7 h, T8 i) // TArgs
            {
                infunc.Invoke(a, b, c, d, e, f, g, h, i); // TParams
                yield break;
            }

            return foo;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7, T8> operator +(CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7, T8> evt, Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, IEnumerator> listener)
        {
            if(evt == null) { evt = new(); }

            if(!evt.listeners.Contains(listener))
            {
                evt.listeners.Add(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7, T8> operator +(CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7, T8> evt, Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> listener)
        {
            return evt + Wrapper(listener);
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7, T8> operator -(CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7, T8> evt, Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, IEnumerator> listener)
        {
            if(evt == null) { return null; }

            if (!evt.listeners.Contains(listener))
            {
                evt.listeners.Remove(listener);
            }

            return evt;
        }

        public static CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7, T8> operator -(CoroutineEvent<T0, T1, T2, T3, T4, T5, T6, T7, T8> evt, Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> listener)
        {
            return evt - Wrapper(listener);
        }
    }

}
