import os

template = '''    public class CoroutineEvent<%s>
    {
        public class EventEntry : IComparable
        {
            public string MethodName;
            public object Target;
            public int Priority;

            public Func<%s, IEnumerator> Listener => _listener;
            private Func<%s, IEnumerator> _listener;

            public EventEntry(Func<%s, IEnumerator> foo, int priority = 0)
            {
                MethodName = foo.Method.Name;
                Target = foo.Target;
                Priority = priority;

                _listener = foo;
                
                Debug.Log($"Created EventEntry from {Target}.{MethodName} with priority {Priority}");
            }

            public void RestoreListener()
            {
                MethodInfo foo = null;
                Type type = Target.GetType();
                while (foo == null && type != null)
                {
                    foo = type.GetMethod(MethodName,
                        BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance|BindingFlags.Static);
                    type = type.BaseType;
                }
                
                if (foo != null)
                {
                    _listener = (Func<%s, IEnumerator>)Delegate.CreateDelegate(
                        typeof(Func<%s, IEnumerator>), Target, (MethodInfo)foo);
                }
                else
                {
                    Debug.LogError($"Failed to restore event: {Target}||{MethodName}");
                }
            }

            public override int GetHashCode()
            {
                return _listener.GetHashCode();
            }

            public int CompareTo(object obj)
            {
                if (obj == null) return 1;
                return this.Priority.CompareTo((obj as EventEntry)?.Priority);
            }

            public override bool Equals(object obj)
            {
                return _listener == (obj as EventEntry)?._listener;
            }
        }
        
        [SerializeField]
        private PrioritySet<EventEntry> listeners = new();

        public IEnumerator Invoke(params object[] vs)
        {
            foreach (var e in listeners.List.ToList())
            {
                yield return new JumpIn((IEnumerator)e.Listener.DynamicInvoke(vs));
            }
            yield break;
        }

        public void AddListener(Func<%s, IEnumerator> listener, int priority = 0)
        {
            EventEntry entry = new EventEntry(listener, priority);
            listeners.AddUnique(entry);
        }

        public void RemoveListener(Func<%s, IEnumerator> listener)
        {
            EventEntry entry = new EventEntry(listener);
            listeners.Remove(entry);
        }

        public void RestoreListener()
        {
            foreach (var e in listeners.List)
            {
                e.RestoreListener();
            }
        }
    }
'''

with open("CoroutineEvent.cs", "w") as f:
    f.write(
'''// Code generated by CoroutineEventCodeGen.py

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace miniRAID
{
''')

    for i in range(1,10):
        TTypes = ", ".join(["T%d" % j for j in range(i)])
        TArgs = ", ".join(["T%d %s" % (j, chr(ord('a') + j)) for j in range(i)])
        TParams = ", ".join(["%s" % chr(ord('a') + j) for j in range(i)])

        code = template % (TTypes, TTypes, TTypes, TTypes, TTypes, TTypes, TTypes, TTypes)

        f.write(code + "\n")

    f.write(
'''}
''')
